spring:
  application:
    name: todo

  datasource:
    url: jdbc:mysql://localhost:3306/todo_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: my-secret-key-for-jwt-token-project-2026-sanghyup
  expiration: 3600000